[package]
name = "esm_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wyz = "0.5.0"
bytes = "1.1.0"
esm_utils = { path = "../esm_utils" }

